### ISSUE TITLE
Run container in host network instead of bridge to allow DLNA discovery

### ISSUE THREAD

**Issue by tophee** [linuxserver/docker-emby#27]
## Expected Behavior
Containerized Emby + DLNA plugin should discover DLNA devices (like TVs), just like it does when installed outside a container

## Current Behavior
When using the provided Docker composer snippet, it does not see my Panasonic Viera DT60 series TV, i.e. it is not offered as a device that can be streamed to (It does, however, see the Chromecast).

## Command used to create docker container (run/create/compose/screenshot)
---
version: "2.1"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvshows:/data/tvshows
      - /path/to/movies:/data/movies
      - /path/for/transcoding:/transcode #optional
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped

## Suggestion
I managed to fix this easily by changing `network_mod` to `"host"`. My suggestion is that this should be the default setting, i.e. include `network_mode: "host"` in the yaml-snippet.

**Comment by aptalca** [comment]
For plex, we recommended host, but got a ton of requests for bridge networking.

For this we recommend bridge, but the user can use it with host networking if they like. 

At the end of the day, we have to recommend one or the other and for every user who prefers one, there is another user who prefers the other.

**Comment by tophee** [comment]
I completely understand that "either way is wrong". 

What I'd suggest, then, is to add  something like this to the yam snippet:

    # network_mode: "host" # optional. Uncomment if you want to use DNLA discovery

**Comment by dfalt974** [comment]
use macvlan network
