### ISSUE TITLE
Optional Transcode Path Wrong?

### ISSUE THREAD

**Issue by coolspot18** [linuxserver/docker-emby#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Documentation states that  -v /path/for/transcoding:/transcode to set the transcoding path, however /transcode is not the container's transcoding path but rather the folder name is /config/transcoding-temp?

User must also set transcoding path in Emby transcoding settings to /transcode manually to use the mapped path.

## Expected Behavior

Setting  -v /path/for/transcoding:/transcode will assign the transcoding path in Emby.

## Current Behavior

Mapped path  -v /path/for/transcoding:/transcode is not used by Emby unless also manually configured in Emby's transcoding settings.

## Steps to Reproduce
1. Set  -v /path/for/transcoding:/transcode in docker compose or Portainer
2. Launch container
3. Start video stream
4. Check /path/for/transcoding on docker host to see if files are being written in there - no files will be written in this folder.

**Comment by tobbenb** [comment]
You have to configure emby yourself. It's not done automatically, so there is nothing wrong with the container.

**Comment by coolspot18** [comment]
Yes, but I think the documentation should make a note to manually configure the path - otherwise, why show the /transcode path as the example?
