### ISSUE TITLE
VAAPI failed to initialize

### ISSUE THREAD

**Issue by bigbrozer** [linuxserver/docker-emby#41]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

VAAPI device (AMD Radeon Vega 3) is initializing correctly allowing hardware accel for encoding.

## Current Behavior

Unable to determine since when the problem occurs (it was working pretty well), but looking at the `hardware_detection-*.txt` log this is showing:

```json
"Devices": [
    {
        "DeviceIndex": 0,
        "DeviceInfo": {
            "VendorId": 4098,
            "DeviceId": 5597,
            "SubsytemVendorId": 4098,
            "SubsytemDeviceId": 5597,
            "DevPath": "/sys/bus/pci/devices/0000:38:00.0",
            "DrmCard": "/dev/dri/card0",
            "DrmRender": "/dev/dri/renderD128",
            "IsEnabled": 1,
            "IsBootVga": 1,
            "Error": {
                "Number": -1,
                "Message": "Failed to initialize VA /dev/dri/renderD128. Error -1"
            }
        }
    }
]
```

## Steps to Reproduce

I have made an attempt to fix this issue as it seems related to the `export LD_LIBRARY_PATH="${APP_DIR}"` within the run script.

1. Install **vainfo** in the container with `apt-get install vainfo` as root.
2. Docker exec as `abc` user and run `vainfo`:

```plain
abc@emby:/$ vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Mesa Gallium driver 20.2.6 for AMD RAVEN (DRM 3.40.0, 5.11.1-arch1-1, LLVM 11.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

3. It looks good. Now, source variables which are loaded by the run script `/etc/services.d/emby/run`:

```bash
APP_DIR="/app/emby"
export LD_LIBRARY_PATH="${APP_DIR}"
export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri:"${APP_DIR}"/dri
```

4. Run again `vainfo`:

```bash
abc@emby:/$ vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva error: dlopen of /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so failed: /app/emby/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/x86_64-linux-gnu/libLLVM-11.so.1)
libva info: Trying to open /app/emby/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

5. Run `/app/emby/ffdetect vaenc`:

```bash
abc@emby:/$ /app/emby/ffdetect vaenc
ffdetect version 4.3.0-emby_2020_05_23 Copyright (c) 2018-2019 softworkz for Emby LLC
  built with gcc 8.3.0 (crosstool-NG 1.24.0)
  configuration: --cc=x86_64-emby-linux-gnu-gcc --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --disable-amf --disable-debug --disable-doc --disable-ffplay --disable-vdpau --disable-xlib --enable-fontconfig --enable-gnutls --enable-gpl --enable-iconv --enable-libass --enable-libdav1d --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libzvbi --enable-pic --enable-version3 --enable-libx265 --enable-cuda-llvm --enable-cuvid --enable-libmfx --enable-nvdec --enable-nvenc --enable-vaapi --extra-libs='-ldrm -lva-drm' --enable-cross-compile --cross-prefix=x86_64-emby-linux-gnu- --arch=x86_64 --target-os=linux --pkg-config=pkg-config --pkg-config-flags=--static --enable-shared --disable-static
  libavutil      56. 36.100 / 56. 36.100
GetDeviceName: unable to open pci.ids file 
GetDeviceName unable to load pci.ids file
[DEVICE]
DeviceIndex=0
DEVICEINFO:VendorId=4098
DEVICEINFO:DeviceId=5597
DEVICEINFO:SubsytemVendorId=4098
DEVICEINFO:SubsytemDeviceId=5597
DEVICEINFO:DevPath=/sys/bus/pci/devices/0000:38:00.0
DEVICEINFO:DrmCard=/dev/dri/card0
DEVICEINFO:DrmRender=/dev/dri/renderD128
DEVICEINFO:IsEnabled=1
DEVICEINFO:IsBootVga=1
DEVICEINFO:ERROR:Number=-1
DEVICEINFO:ERROR:Message=Failed to initialize VA /dev/dri/renderD128. Error -1
[/DEVICE]
```

## Workaround

Modify `LD_LIBRARY_PATH` such as:

```diff
- export LD_LIBRARY_PATH="${APP_DIR}"
+ export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:${APP_DIR}"
```

Patch commands for live testing using docker exec (as root) within the container:

```bash
sed -i -r -e 's/^(export LD_LIBRARY_PATH)="(.*)"/\1="\/usr\/lib\/x86_64-linux-gnu:\2"/g' /var/run/s6/services/emby/run
kill $(pgrep EmbyServer)
```

VAAPI is working well :tada: 

## Environment

**OS:** Archlinux
**CPU architecture:** x86_64
**How docker service was installed:** Docker is installed on a Archlinux system by the [docker](https://archlinux.org/packages/community/x86_64/docker/) community package.

## Command used to create docker container (run/create/compose/screenshot)

Using docker-compose:

```yaml
version: "3.7"

services:
  app:
    image: "linuxserver/emby:4.5.4.0-ls78"
    restart: "unless-stopped"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
      - "/dev/dri/card0:/dev/dri/card0"
    volumes:
      - "config:/config"
      - "..." # Data mount points
    network_mode: "host"
```

## Docker logs

[emby_docker.log](https://github.com/linuxserver/docker-emby/files/6160266/emby_docker.log)

**Comment by XBigTK13X** [comment]
I was seeing the same error running Emby in this container. The host has an RX 550 and the latest amdgpu-pro drivers installed. After adding the changes to `LD_LIBRARY_PATH` suggested above, hardware accelerated transcoding started working.

**Comment by JBou** [comment]
This fix enables hardware transcoding on Unraid 6.9.1 using an AMD iGPU (e.g. AMD Ryzen 7 PRO 4750G). Would like to see it getting merged. Thanks @bigbrozer 🎉

**Comment by JBou** [comment]
I created a Docker Mod that fixes this problem until it gets merged. It's based on the workaround above.
Here is the source code: https://github.com/JBou/docker-mods/tree/docker-emby-fix-vaapi
It can be enabled by adding an environment variable to the `docker-emby` container like this: `DOCKER_MODS=jbouhd/docker-mods:docker-emby-fix-vaapi`

**Comment by bigbrozer** [comment]
Just tested with 4.6.1.0-ls85 release and I'm not able to reproduce the error... hardware acceleration is detected correctly. Maybe an upstream change ? It appears that the work around with `LD_LIBRARY_PATH` is not needed as `${APP_DIR}` contains all libs...

Let me know if this is the same for you using the new version, I will close this issue if not relevant anymore.

**Comment by RainmakerRaw** [comment]
I'm seeing this same error on a Synology DS218+, with Intel integrated GPU. I normally run the container (via docker-compose) as my `linuxserver` user (UID 1033), which has access to all media folders etc.  I noticed today that this no longer allows access to hardware acceleration (it worked in the past).  

Running the Docker container as root (UID 0) fixes the issue and allows detection of the card. The docs for the container say the 'abc' user gets permissions auto-configured, and until now that's been true. With 4.6.0.5 and 4.6.1.0 it hasn't worked - but I don't know at which version it stopped working as I only noticed it today (when trying to transcode hevc to h264).

**Comment by aptalca** [comment]
abc permissions are auto configured "as long as you map the devices correctly", and that the OS doesn't do something silly like set the group owner on them as root.

The OP here has not mapped the devices correctly for instance.

**Comment by RainmakerRaw** [comment]
> the OS doesn't do something silly like set the group owner on them as root.

That may be my issue. I didn't open a new one as the OP basically covered it. AFAIK Synology does weird and wonderful things with the group permissions on `/dev/dri` unfortunately. I'll just stick to running as root for this container, as any permission mods in Synology are reset at reboot, so it's the easiest solution.

**Comment by aptalca** [comment]
Yeah, to clarify, the video devices need to be owned by `root:video` or `root:render`, basically some specific group other than `root` so that one can add their user to the `video` or `render` group and have access to the video device. That is precisely what we do inside the container.

Most OSes do that. I guess Syno does not.

**Comment by JBou** [comment]
> Just tested with 4.6.1.0-ls85 release and I'm not able to reproduce the error... hardware acceleration is detected correctly. Maybe an upstream change ? It appears that the work around with `LD_LIBRARY_PATH` is not needed as `${APP_DIR}` contains all libs...
> 
> Let me know if this is the same for you using the new version, I will close this issue if not relevant anymore.

I can confirm that it is working for me now, too, using the new version of emby! I don't have to use the workaround anymore. So i think this should be resolved.

**Comment by bigbrozer** [comment]
Thanks for the feedback. Closing.
