### ISSUE TITLE
docker cannot start using my existing config... help needed

### ISSUE THREAD

**Issue by theoneakta** [linuxserver/docker-emby#44]
Can you please help me

i am using a Dockerfile to set the volume and a run.sh to run the container

in the Docker file my volume is set to /config

should i put the full path or dockerfile see where the file is?

/opt/docker/docker-emby

-rw-r--r--.    1 root root    20480 Jun 25 23:59 activitylog.db
-rw-r--r--.    1 root root    32768 Jun 25 23:59 activitylog.db-shm
-rw-r--r--.    1 root root  1203072 Jun 25 23:59 activitylog.db-wal
-rw-r--r--.    1 root root    28672 Jun 25 23:59 authentication.db
-rw-r--r--.    1 root root    32768 Jun 25 23:59 authentication.db-shm
-rw-r--r--.    1 root root  4128272 Jun 25 23:59 authentication.db-wal
drwxr-xr-x.   13  911  911      206 Jul  8 20:14 config
-rw-r--r--.    1 root root      131 Jun 25 23:59 connect.txt
drwxr-xr-x.    2 root root        6 Jul  8 19:26 custom-cont-init.d
drwxr-xr-x.    2 root root        6 Jul  8 19:26 custom-services.d
drwxr-xr-x.    2  911  911     4096 Jul  8 20:22 data
drwxr-xr-x.   17 root root     4096 Jun 25 23:59 devices
-rw-r--r--.    1 root root       35 Jun 25 23:59 device.txt
-rw-r--r--.    1 root root    12288 Jun 25 23:59 displaypreferences.db
-rw-r--r--.    1 root root    32768 Jun 25 23:59 displaypreferences.db-shm
-rw-r--r--.    1 root root    74192 Jun 25 23:59 displaypreferences.db-wal
-rw-r--r--.    1 root root     1750 Jul 10 01:28 Dockerfile
-rw-r--r--.    1 root root     1936 Jun 23 00:20 Dockerfile.aarch64
-rw-r--r--.    1 root root     1936 Jun 23 00:20 Dockerfile.armhf
drwxr-xr-x. 1005 root root    24576 Jun 25 23:59 fanart-movies
drwxr-xr-x.   19 root root      240 Jun 25 23:59 fanart-tv
drwxr-xr-x.    2 root root     4096 Jun 25 23:59 ffmpeg
drwxr-xr-x.    2 root root      166 Jun 25 23:59 httpclient
drwxr-xr-x.    3 root root       28 Jun 25 23:59 images
-rw-r--r--.    1 root root    46461 Jun 23 00:20 Jenkinsfile
-rw-r--r--.    1 root root      732 Jun 23 00:20 jenkins-vars.yml
-rw-r--r--.    1 root root        7 Jun 25 23:59 lastversion.txt
-rw-r--r--.    1 root root 32706560 Jun 25 23:59 library.db
-rw-r--r--.    1 root root    32768 Jun 25 23:59 library.db-shm
-rw-r--r--.    1 root root 15103952 Jun 25 23:59 library.db-wal
-rw-r--r--.    1 root root    35149 Jun 23 00:20 LICENSE
drwxr-xr-x.    2  911  911   188416 Jul  8 20:25 logs
-rw-r--r--.    1 root root   143663 Jun 25 23:59 news.json
drwxr-xr-x.    2 root root     4096 Jun 25 23:59 omdb
-rwxr-xr-x.    1 root root     4251 Jun 23 00:20 package_versions.txt
drwxr-xr-x.    2  911  911     4096 Jul  8 19:26 plugins
-rw-r--r--.    1 root root    18056 Jun 23 00:20 README.md
-rw-r--r--.    1 root root     6345 Jun 23 00:20 readme-vars.yml
drwxr-xr-x.    3 root root       17 Jun 23 00:20 root
-rw-r--r--.    1 root root      111 Jun 26 00:58 run.sh
drwxr-xr-x.    2 root root     4096 Jun 25 23:59 ScheduledTasks
drwxr-xr-x.    3 root root       15 Jun 25 23:59 subtitles
-rw-r--r--.    1 root root     2959 Jun 25 23:56 system.xml
drwxr-xr-x.    2 root root     4096 Jun 25 23:59 temp
drwxr-xr-x.   95 root root     4096 Jun 25 23:59 tmdb-collections
drwxr-xr-x.  912 root root    24576 Jun 25 23:59 tmdb-movies2
drwxr-xr-x.   19 root root      224 Jun 25 23:59 tmdb-tv
drwxr-xr-x.   19 root root      256 Jun 25 23:59 tvdb
drwxr-xr-x.    4 root root       86 Jun 25 23:56 users
-rw-r--r--.    1 root root    12288 Jun 25 23:59 users.db
-rw-r--r--.    1 root root    32768 Jun 25 23:59 users.db-shm
-rw-r--r--.    1 root root   927032 Jun 25 23:59 users.db-wal
drwxr-xr-x.    4 root root       30 Jun 26 00:39 volumes
-rw-r--r--.    1 root root       19 Jun 25 23:59 wan.dat

in Dockerfile at the end:

# ports and volumes
EXPOSE 8096 8920
VOLUME /config
VOLUME /movies
VOLUME /tv
#DEVICE /dev/dri:/dev/dri

Thanks

Michel Mondor

**Comment by Roxedus** [comment]
You are running with modifications we don't support. You are also leaving out important parts from the issue template.

**Comment by theoneakta** [comment]
So I need to stage the emby everytime?

I can't use an existing config and users?



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Roxedus** [comment]
wdym stage? your instance keeps persistence if you mount /config

**Comment by theoneakta** [comment]
Do I need to put the full path of the config folder?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theoneakta** [comment]
Ok I had to rebuild with the full path

With the docker file pointing to the config

And the media

So now its much easier!

Thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
