### ISSUE TITLE
Unraid issues with optional parameters

### ISSUE THREAD

**Issue by diegomontanaduarte** [linuxserver/docker-emby#46]
Every time that I got an update from Emby docker app on Unraid the Raspberry Pi optional parameters is being duplicated on the template and then the update failed since I don't use Raspberry Pi hardware acceleration. To workaround this issue I have to edit the docker options and remove all optional parameters, the last time I needed to remove more than 30 duplicated fields

/opt/vc/lib
/dev/vchiq
/dev/video10
/dev/video11
/dev/video12

![image](https://user-images.githubusercontent.com/2682853/147407326-a1305f26-0cc8-494d-893a-0d396f9c5e83.png)

**Comment by diegomontanaduarte** [comment]
These fields is still getting duplicated. For example, If I click in "Check for Updates" button in Unraid Docker page fields are being duplicated.

**Comment by diegomontanaduarte** [comment]
@Roxedus could you please take a look into this issue again, still persists.

**Comment by Roxedus** [comment]
Disable the sync manually then

**Comment by diegomontanaduarte** [comment]
How can I disable the sync manually?

**Comment by Roxedus** [comment]
https://forums.unraid.net/topic/38619-docker-template-xml-schema/?do=findComment&comment=825087

**Comment by diegomontanaduarte** [comment]
OK, it seems setting the TemplateURL to false resolved the issue, @Roxedus thanks for your help!

**Comment by jeff15110168** [comment]
I'm also having this issue. I had ~100 copies of those 6-7 variables. I'm not following how to implement this templateURL solution. Sorry for beginner unraid question. @diegomontanaduarte do you mind posting the idiot-proof steps on how to do this via docker tab in unraid?
