### ISSUE TITLE
Don't chown /data (user's media)

### ISSUE THREAD

**Issue by srd424** [linuxserver/docker-emby#51]
Please excuse me not following the template, but it's not really appropriate.

The container init scripts currently chown both /config (reasonable) and /data - the latter seems very unreasonable. The jellyfin container also did this; following the discussion in https://github.com/linuxserver/docker-jellyfin/issues/62 this has been changed. The plex container to my knowledge has never done this. I think for consistency and sanity we should change it here too.

**Comment by lateparty** [comment]
My emby is no longer starting since the migration to s6v3. The init script fails to chown anything in /data/ and then doesn't continue loading. Emby is not a critical app for me, I just keep it as a backup option but I would like some attention on this issue so it is resolved.

**Comment by srd424** [comment]
If you grab the init script from from the PR (https://github.com/srd424/docker-emby/blob/58c28a4f50fdad69f3bf4971321180c8197e1828/root/etc/cont-init.d/30-config) and save it somewhere, you can bind mount into the container using
`-v /path/to/modified/script:/etc/s6-overlay/s6-rc.d/init-emby/run` in your docker/podman args.

But yes, would be good to see this fixed, particularly now it seems to actually fail with a r/o media volume.
