### ISSUE TITLE
Emby Nightly Builds

### ISSUE THREAD

**Issue by sgtcoder** [linuxserver/docker-emby#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Desired Behavior
Emby 4.7.9.0 was released yesterday, but the latest linuxserver build is behind. It would be nice to get a nightly image build of the latest Emby so we can stay more up to date.

## Current Behavior
It seems like builds are a little bit delayed.

## Alternatives Considered
Probably possible to manually update Emby, but if you were to reboot the version will rollback.

**Comment by j0nnymoe** [comment]
Builds are delayed because we have wait for a specific asset to be added to the release post here https://github.com/MediaBrowser/Emby.Releases/releases .

Why they don't release all the assets at once is beyond me.

**Comment by sgtcoder** [comment]
I see what you mean and that completely makes sense. I opened up a thread on Emby side to see what they can do: https://emby.media/community/index.php?/topic/113630-missing-assets-on-latest-buildsreleases/

**Comment by j0nnymoe** [comment]
Thanks. We use the rpm files (I think due to it including all the libs we need) but yea, would be nice if they released all at once.

**Comment by aptalca** [comment]
I asked a few times on their forum whether the asset release process was manual or automated. Never got a clear answer. It's either manual and they forget to upload some of them, or they have a ci that skips failed artifacts and has frequent failures because every beta release has some artifacts missing for hours or days, and it's different ones each time.

**Comment by sgtcoder** [comment]
No promises, but they are going to try and get better at it:
```
Yes we can try to get better at making them all available at once. Thanks.
```

--


<br class="Apple-interchange-newline">

**Comment by j0nnymoe** [comment]
Closing.
