### ISSUE TITLE
[FEAT] Add support for MediaInfo plugin on am64

### ISSUE THREAD

**Issue by DaveO16176** [linuxserver/docker-emby#64]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The [MediaInfo plugin](https://github.com/Cheesegeezer/MediaInfoWiki/wiki) enables Emby to properly display media tags including HDR, Vision, Atmos, etc.  The current build does not include all the libraries necessary to use the plugin on amd64.

### Reason for change

The MediaInfo plug requires [MediaInfo](https://mediaarea.net/en/MediaInfo), [MKVToolNix](https://mkvtoolnix.download/) and [Roku's BIF Tool](https://developer.roku.com/en-gb/docs/developer-program/media-playback/trick-mode/bif-file-creation.md).  MediaInfo and MKVToolnix are required for media tags generation and Roku's BIF Tool is required to properly generate thumbnail and chapter images when using HDR sources and displayed on a SDR screen or a HDR screen before playback begins (*) - look generally colourless and very 'off'.

**Comment by aptalca** [comment]
A mod is more appropriate here:
https://github.com/linuxserver/docker-mods/
