### ISSUE TITLE
[BUG] beta v4.8.0.34 was released several days ago..

### ISSUE THREAD

**Issue by wynterca** [linuxserver/docker-emby#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new version usually is built within a day.. but hasn't been.

### Expected Behavior

The new version should be built.

### Steps To Reproduce

Look on github in available tags

### Environment

```markdown
- OS: Github
```

### CPU architecture

x86-64

### Docker creation

```bash
..
```

### Container logs

```bash
..
```

**Comment by aptalca** [comment]
Their latest beta release is missing the rpm artifacts that we use to build.
