### ISSUE TITLE
How to run a command before emby starts when starting

### ISSUE THREAD

**Issue by wmbin** [linuxserver/docker-emby#68]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

How to run a command before emby starts when starting

### Reason for change

Map the Nvidia driver into the container, ldconfig needs to be run before Emby is called.

**Comment by aptalca** [comment]
What makes you think you need to run that?

https://xyproblem.info/

**Comment by wmbin** [comment]
@aptalca 
`NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.`

I have found how to enable the executable file, /etc/cont-init.d/.
