### ISSUE TITLE
[FEAT] Add ffmpeg package in the docker image

### ISSUE THREAD

**Issue by bboutier** [linuxserver/docker-emby#82]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add by default the ffmpeg package inside the docker image.

### Reason for change

As using this great docker image inside the helm chart provided by TrueChart (https://truecharts.org/charts/stable/emby/) for TrueNas SCALE deployment, i have some clients (like a smart Tv) which are unable to transcode some media locally.
In this situation, these clients  require the emby server to do it, which can use the ffmpeg package.

Thanks :)

### Proposed code change

Impact the Dockerfile to add at docker build stage the ffmpeg package.

**Comment by j0nnymoe** [comment]
As with all the media server's, emby provide their own build of ffmpeg and it is included: https://github.com/linuxserver/docker-emby/blob/c0acdfeda981255fcfdcc107ccf8f99129857d1f/package_versions.txt#L12

**Comment by aptalca** [comment]
It also doesn't seem to use our image: https://github.com/truecharts/charts/blob/master/charts/stable/emby/values.yaml#L2
