### ISSUE TITLE
[BUG] First launch after container update stuck on [migrations] messages

### ISSUE THREAD

**Issue by edrock200** [linuxserver/docker-emby#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When updating emby container image, first launch just hangs with only this in the docker log:

[migrations] started
[migrations] no migrations found

A restart of the container then proceeds per usual.

### Expected Behavior

No hang after container update

### Steps To Reproduce

Have an existing emby instance.
Delete existing emby container
Redeploy emby with /config pointing to your existing emby instance

### Environment

```markdown
- OS:Ubuntu 22.04/Docker, pgid/puid set to 1000:1000 vs root
- How docker service was installed: via apt
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
--name "emby" \
--restart="unless-stopped" \
--hostname="emby" \
--device="/dev/dri:/dev/dri" \
--network="bridge" \
-e "UID=1000" \
-e "GID=1000" \
-e "GUID=1000" \
-e "PUID=1000" \
-e "AMDGPU_IDS=/share/libdrm/amdgpu.ids" \
-e "FONTCONFIG_PATH=/etc/fonts" \
-e "GIDLIST=2" \
-e "HOME=/root" \
-e "LANG=en_US.UTF-8" \
-e "LANGUAGE=en_US.UTF-8" \
-e "PCI_IDS_PATH=/share/hwdata/pci.ids" \
-e "LD_LIBRARY_PATH=/lib:/system" \
-e "LIBVA_DRIVERS_PATH=/lib/dri" \
-e "LSIO_FIRST_PARTY=true" \
-e "OCL_ICD_VENDORS=/etc/OpenCL/vendors" \
-e "VIRTUAL_ENV=/lsiopy" \
-e "XDG_CACHE_HOME=/config/cache" \
-e "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0" \
-e "S6_STAGE2_HOOK=/docker-mods" \
-e "S6_VERBOSITY=1" \
-e "TZ=EET" \
-e "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
-e "TERM=xterm" \
-e "LANG=C.UTF-8" \
-e "LC_ALL=C.UTF-8" \
-e "HOME=/config" \
-p "8096:8096" \
-v "/dev/shm:/dev/shm" \
-v "/mnt/local/transcodes/emby:/transcode" \
-v "/mnt/unionfs/Media:/mnt/unionfs/Media:ro" \
-v "/opt/emby:/config" \
lscr.io/linuxserver/emby:latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
```

**Comment by aptalca** [comment]
Remove all those vars from your docker run. The only ones you should be setting are listed in the readme

**Comment by edrock200** [comment]
> Remove all those vars from your docker run. The only ones you should be setting are listed in the readme

So I removed the env vars less the ones listed as supported in the readme, but it still does the same thing on initial deployment, a restart seems to get it going again.

**Comment by homerr** [comment]
It could be that when you created the container with all of those env settings, something is stuck somewhere. The only way to sort this out would be to start from fresh which I wouldn't want to do, so I'm afraid the best thing to do is manage this with the manual restart until you are in a place to reinstall the container.
