### ISSUE TITLE
[FEAT] RK3588/3588s devices - MPP & RGA hardware acceleration for transcoding

### ISSUE THREAD

**Issue by hellznrg** [linuxserver/docker-emby#98]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I run a Kubernetes cluster with [NanoPI R6S](https://www.friendlyelec.com/index.php?route=product/product&product_id=289) devices which support "8K@60fps H.265 and VP9 decoder, 8K@30fps H.264 decoder, 4K@60fps AV1 decoder, 8K@30fps H.264 and H.265 encoder".

There is a fork of ffmpeg ( [ffmpeg-rockchip](https://github.com/nyanmisaka/ffmpeg-rockchip?tab=readme-ov-file) ) which adds ability to use the RK devices hardware acceleration.

Is it possible for linuxserver/docker-emby to add support for HW acceleration for RK devices?

### Reason for change

At the moment, my x265 videos seem to be doing software decoding and performance is very poor with lots of skips, and transcoding is hopeless.

### Proposed code change

Will it work if I compile ffmpeg-rockchip and create a new docker image based off of linuxserver/emby with the new ffmpeg binary?

**Comment by hellznrg** [comment]
There is another fork of ffmpeg for RK devices [ffmpeg-rk](https://github.com/jjm2473/ffmpeg-rk) but I don't know how it's different from ffmpeg-rockchip. I'm not very savvy when it comes to this sort of thing.

**Comment by aptalca** [comment]
Emby uses its own ffmpeg binary. We don't install it in the image. So this request should be made to Emby.

Also, even if you were to replace the binary in there with a custom one, the necessary transcoding args may be different for that gpu, which would require changes to Emby itself.

**Comment by hellznrg** [comment]
Thanks for the info! I have decided to go with jellyfin, since it seems to already have hwacceleration for rockchip OOTB.
